version: '3.1'

services:
  # whu-library-seat (3 services)
  seat-db:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-db:1.0.0
    container_name: seat-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    environment:
      TIME_ZONE: ${TIME_ZONE}
      MYSQL_DATABASE: seat-records
      MYSQL_USER: whu-lib
      MYSQL_PASSWORD: Ab12345678..c
      MYSQL_ROOT_PASSWORD: ${SEAT_DB_ROOT_PASSWD}
    volumes:
      - seat-db-v:/var/lib/mysql/
      - ./whu-library-seat/db_init_scripts/:/docker-entrypoint-initdb.d/
    networks:
      - seat-network
  seat-recorder:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-records:1.0.0
    container_name: seat-recorder
    environment:
      TIME_ZONE: ${TIME_ZONE}
    restart: always
    depends_on:
      - seat-db
    networks:
      - seat-network
  seat-ghauth:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-ghauth:1.0.0
    container_name: seat-ghauth
    environment:
      TIME_ZONE: ${TIME_ZONE}
      WHU_SEAT_CLIENT_SCERET: ${SEAT_GHAUTH_CLIENT_SCERET}
    restart: always
    networks:
      - seat-network
    
  # shadowsocks (1 service)
  shadowsocks:
    image: mrjin/shadowsocks:alpine
    container_name: shadowsocks
    restart: always
    environment:
      - TIME_ZONE=${TIME_ZONE}
      - PASSWORD=${SHADOWSOCKS_PASSWD} 
      - METHOD=chacha20
      - TUN_PORT=80
    restart: always
    networks:
      - shadowsocks-network

  # global nginx
  nginx:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-nginx:1.0.0
    container_name: global-nginx
    environment:
      - TIME_ZONE=${TIME_ZONE}
      - CER_BOT_DOMAIN=${NGINX_SSL_DOMAIN}
      - CER_BOT_EMAIL=${NGINX_SSL_EMAIL}
    restart: always
    ports:
      - ${NGINX_SSL_PORT}:443
      - ${NGINX_SHADOWSOCKS_PORT}:1984
    volumes:
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/assets/:/home/nginx/assets/
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - seat-recorder
      - seat-ghauth
      - shadowsocks
    networks:
      - seat-network
      - shadowsocks-network

volumes:
  seat-db-v:

networks:
  seat-network:
  shadowsocks-network:
