version: '3.5'

services:
  # seat (4 services)
  seat-db-backup:
    image: mysql
    container_name: seat-db-backup
    command: echo "Data-only container for seat-db"
    volumes:
      - seat-db-v:/var/lib/mysql/:ro

  seat-db:
    image: mysql
    container_name: seat-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_DATABASE: seat-records
      MYSQL_USER: whu-lib
      MYSQL_PASSWORD: Ab12345678..c
      MYSQL_ROOT_PASSWORD: ${SEAT_DB_ROOT_PASSWD}
    depends_on:
      - seat-db-backup
    volumes:
      - seat-db-v:/var/lib/mysql/
      - ./seat/db_init_scripts/:/docker-entrypoint-initdb.d/
    networks:
      - seat-network

  seat-recorder:
    image: cstao/seat-records:1.0.1
    container_name: seat-recorder
    environment:
      DATABASE_HOST: seat-db
    restart: always
    depends_on:
      - seat-db
    networks:
      - seat-network

  seat-ghauth:
    image: cstao/seat-ghauth:1.1.0
    container_name: seat-ghauth
    environment:
      WHU_SEAT_CLIENT_SCERET: ${SEAT_GHAUTH_CLIENT_SCERET}
    restart: always
    networks:
      - seat-network


  # portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --admin-password '${PORTAINER_ADMIN_PASSWD_HASHED}'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-v:/data
    networks:
      - portainer-network


  # gallery
  gallery:
    image: alterway/docker-image-gallery
    container_name: gallery
    environment:
      GALLERY_TITLE: My Gallery
    restart: always
    volumes:
      - ./gallery/rewrite/index.html:/fgallery/view/index.html:ro
      - ./gallery/rewrite/favicon.png:/fgallery/view/favicon.png:ro
      - ./gallery/images/:/images/:ro
    networks:
      - gallery-network


  # v2ray (2 services)
  v2ray:
    image: cstao/docker-v2ray:v2.0.0
    container_name: v2ray
    environment:
      REPLACEMENTS: ${V2RAY_REPLACEMENTS}
    command: ["bash", "-c", "/etc/v2ray/start.sh"]
    restart: always
    volumes:
      - ./v2ray/config.tmpl:/etc/v2ray/config.tmpl:ro
      - ./v2ray/start.sh:/etc/v2ray/start.sh
      - ./v2ray/logs/:/var/log/v2ray/
      - ./v2ray/print/:/var/v2ray/print/
    networks:
      - v2ray-network

  v2ray-print:
    image: cstao/docker-v2ray-print
    container_name: v2ray-print
    command: ["-a", "world.cs-tao.cc", "-f", "ws", "-m", "port:${CADDY_SSL_PORT}", "-m", "tls:tls", "-m", "ps:Virmach"]
    environment:
      SAY_GOODBYE: "\\033[32mWelcome to the new world! Now you can fly to any place you want. Enjoy yourself.\\033[0m\n"
    volumes:
      - ./v2ray/print/:/var/v2ray/volume/
    depends_on:
      - v2ray


  # caddy
  caddy:
    image: abiosoft/caddy
    container_name: caddy
    environment:
      ACME_AGREE: "true"
      DOMAIN_ASSETS: ${CADDY_DOMAIN_ASSETS}
      DOMAIN_GALLERY: ${CADDY_DOMAIN_GALLERY}
      DOMAIN_PORTAINER: ${CADDY_DOMAIN_PORTAINER}
      DOMAIN_SEAT_GHAUTH: ${CADDY_DOMAIN_SEAT_GHAUTH}
      DOMAIN_SEAT_RECORDER: ${CADDY_DOMAIN_SEAT_RECORDER}
      DOMAIN_V2RAY: ${CADDY_DOMAIN_V2RAY}
      V2RAY_WS_PATH: ${CADDY_V2RAY_WS_PATH}
    restart: always
    ports:
      - ${CADDY_PORT}:80
      - ${CADDY_SSL_PORT}:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
      - ./caddy/caddyfile.d/:/etc/caddyfile.d/:ro
      - ./caddy/ssl/:/root/.caddy/
      - ./caddy/www/:/srv/:ro
      - ./caddy/logs/:/var/logs/
    depends_on:
      - seat-recorder
      - seat-ghauth
      - portainer
      - gallery
      - v2ray
    networks:
      - seat-network
      - portainer-network
      - gallery-network
      - v2ray-network

volumes:
  seat-db-v:
    name: seat-db-data
  portainer-v:
    name: portainer-data

networks:
  default:
    name: services-network
  seat-network:
    name: seat-network
  v2ray-network:
    name: v2ray-network
  portainer-network:
    name: portainer-network
  gallery-network:
    name: gallery-network
