name: Docker Compose CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install docker-compose
      env:
        DOCKER_COMPOSE_VERSION: 1.24.1
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin
    - name: Pull images
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp ci.env .env
        docker login -u cstao -p ${DOCKER_PASSWORD}
        docker login docker.pkg.github.com -u CS-Tao -p ${GITHUB_PASSWORD}
        docker-compose pull
    - name: Run containers
      run: |
        docker-compose up -d
    - name: Deploy docker-compose graph
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: mkdir public cat docker-compose.yml | docker run -i funkwerk/compose_plantuml --link-graph | docker run -i think/plantuml > public/services_graph.svg
